apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: technical-analysis
  namespace: tech-analysis-prod
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  rules:
    - host: your-domain.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: technical-analysis
                port:
                  number: 8000
  tls:
    - hosts:
        - your-domain.example.com
      secretName: tech-analysis-tls
